#!/usr/bin/env python3
"""
Copilot-aware refactor tool:
- Đọc PROJECT_MAP.md để biết mapping module → đích
- Chạy ruff/mypy/pytest nhanh để chấm điểm file 'dùng được'
- Di chuyển file pass về cấu trúc mới (dry-run/commit)
- Sinh stub (docstring + TODO) cho file còn thiếu theo mapping
Usage:
  uv run python tools/refactor/copilot_refactor.py --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
import Exception
import SystemExit
import ValueError
import d
import dict
import e
import int
import issues
import len
import list
import m
import max
import md
import moves
import mp
import p
import print
import results
import s
import src
import str
import sum
import tuple
import x

ROOT = Path(__file__).resolve().parents[2]


@dataclass
class FileScore:
    path: Path
    score: int  # 0..100
    issues: list[str]


MAP_RE = re.compile(r"^\s*-\s*(?P<src>[\w/\.]+)\s*->\s*(?P<dst>[\w/\.]+)", re.M)


def parse_project_map(md: Path) -> dict[str, str]:
    txt = md.read_text(encoding="utf-8", errors="ignore")
    mp: dict[str, str] = {}
    for m in MAP_RE.finditer(txt):
        mp[m.group("src").strip()] = m.group("dst").strip()
    return mp


def score_file(p: Path) -> FileScore:
    issues: list[str] = []
    score = 100
    try:
        if p.suffix == ".py":
            cp = subprocess.run(["uv", "run", "ruff", "check", str(p)], capture_output=True, text=True)
            if cp.returncode != 0:
                issues.append("ruff")
                score -= 30
            cp2 = subprocess.run(["uv", "run", "mypy", "--hide-error-codes", str(p)], capture_output=True, text=True)
            if cp2.returncode != 0:
                issues.append("mypy")
                score -= 40
        elif p.suffix in (".ts", ".tsx"):
            # best-effort: tsc --noEmit (nếu có)
            tsconfig = ROOT / "desktop_ai_zeta" / "tsconfig.json"
            if tsconfig.exists():
                cp = subprocess.run(
                    ["pnpm", "tsc", "--noEmit", "--pretty", "false", "--project", str(tsconfig)],
                    capture_output=True,
                    text=True,
                )
                if cp.returncode != 0:
                    issues.append("tsc")
                    score -= 40
        else:
            score -= 10
    except Exception as e:
        issues.append(f"exec:{e}")
        score = max(score - 50, 0)
    return FileScore(path=p, score=max(score, 0), issues=issues)


STUB_HEADER = '''"""AUTO-GENERATED STUB
This file was generated by copilot_refactor.py as a scaffold.
TODO: Implement according to Clean Architecture contracts (entities/use-cases/interfaces).
"""
'''


def ensure_stub(dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if not dst.exists():
        dst.write_text(STUB_HEADER, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--map", default=str(ROOT / ".github" / "prompts" / "PROJECT_MAP.md"))
    args = ap.parse_args()

    mapping = parse_project_map(Path(args.map)) if Path(args.map).exists() else {}
    candidates = [
        p
        for p in ROOT.rglob("*")
        if p.suffix in (".py", ".ts", ".tsx") and ".venv" not in str(p) and "node_modules" not in str(p)
    ]

    print(f"Scanning {len(candidates)} files...")
    results: list[FileScore] = []

    for p in candidates[:20]:  # Limit for demo
        try:
            fs = score_file(p)
            results.append(fs)
        except Exception as e:
            print(f"Error scoring {p}: {e}")

    moves: list[tuple[Path, Path]] = []
    for fs in results:
        try:
            rel = fs.path.relative_to(ROOT)
            key = str(rel).replace("\\", "/")
            if key in mapping and fs.score >= 70:
                dst = ROOT / mapping[key]
                moves.append((fs.path, dst))
            elif key in mapping and fs.score < 70:
                dst = ROOT / mapping[key]
                ensure_stub(dst)
        except ValueError:
            # Path not relative to ROOT
            continue

    report = {
        "summary": {
            "total": len(results),
            "pass>=70": sum(1 for x in results if x.score >= 70),
            "stubbed": len([x for x in mapping.values() if (ROOT / x).exists()]),
        },
        "moves": [(str(s), str(d)) for s, d in moves],
        "low_score": [{"file": str(x.path), "score": x.score, "issues": x.issues} for x in results if x.score < 70],
        "mapping_available": len(mapping),
    }
    print(json.dumps(report, indent=2))

    if not args.dry_run:
        for src, dst in moves:
            dst.parent.mkdir(parents=True, exist_ok=True)
            print(f"Moving {src} -> {dst}")
            shutil.move(str(src), str(dst))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
