# Script PowerShell tự động sửa lỗi VS Code Environment
# Generated by diagnose_environment_comprehensive.py

Write-Host "🔧 VS CODE ENVIRONMENT AUTO-FIX" -ForegroundColor Cyan

# 1. Check Python interpreter
Write-Host "`n🐍 Checking Python interpreter..." -ForegroundColor Yellow
$VenvPython = "E:\zeta\.venv\Scripts\python.exe"
if (Test-Path $VenvPython) {
    Write-Host "✅ Python venv found: $VenvPython" -ForegroundColor Green
} else {
    Write-Host "❌ Python venv not found!" -ForegroundColor Red
    exit 1
}

# 2. Reload VS Code window
Write-Host "`n🔄 Reloading VS Code window..." -ForegroundColor Yellow
code --command "workbench.action.reloadWindow"

# 3. Clear extension cache
Write-Host "`n🧹 Clearing extension cache..." -ForegroundColor Yellow
$ExtensionCache = "$env:USERPROFILE\.vscode\extensions"
Get-ChildItem $ExtensionCache -Filter "*.cache" -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue

# 4. Restart extension host
Write-Host "`n🔌 Restarting extension host..." -ForegroundColor Yellow
code --command "workbench.action.restartExtensionHost"

Write-Host "`n✅ Auto-fix completed! Check VS Code status." -ForegroundColor Green
