# Quick setup aliases for ZETA_VN development
# Source this file: . scripts/dev_aliases.sh

alias zeta-bootstrap="scripts/bootstrap_dev.sh"
alias zeta-server="uv run uvicorn zeta_vn.app.main_production:app --reload --host 0.0.0.0 --port 8000"
alias zeta-worker="uv run celery -A zeta_vn.app.worker.celery_app worker -l info"
alias zeta-beat="uv run celery -A zeta_vn.app.worker.celery_app beat -l info"
alias zeta-desktop="cd desktop_ai_zeta && npm run dev"
alias zeta-test="uv run pytest -v"
alias zeta-lint="uv run ruff check ."
alias zeta-format="uv run ruff format ."
alias zeta-typecheck="uv run mypy ."
alias zeta-quality="uv run python tools/master_quality_check.py"
alias zeta-security="uv run python -m zeta_vn.cli.maintenance security sweep"
alias zeta-health="uv run python -m zeta_vn.cli.maintenance health check --detailed"
alias zeta-optimize="uv run python -m zeta_vn.cli.maintenance optimize status"
alias zeta-info="uv run python -m zeta_vn.cli.maintenance system info"
alias zeta-codegen="cd desktop_ai_zeta && npm run codegen:api"
alias zeta-migration="uv run alembic upgrade head"
alias zeta-db="docker run --rm -d --name zeta-pg -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=zeta -p 5432:5432 pgvector/pgvector:pg16"

echo "🚀 ZETA_VN development aliases loaded!"
echo "Usage:"
echo "  zeta-bootstrap    # Quick bootstrap development environment"
echo "  zeta-server       # Start FastAPI development server"
echo "  zeta-desktop      # Start apps/desktop app"
echo "  zeta-quality      # Run full quality checks"
echo "  zeta-health       # Check system health"
echo "  zeta-security     # Run security sweep"
