"""Convert auto-generated barrel __init__.py files from relative to absolute imports.

This script only edits __init__.py files that contain the marker
"AUTO-GENERATED by tools/autobarrel_python.py" to avoid touching manual files.

It replaces patterns like:
  from . import foo as foo
  from .module import Bar
with absolute imports based on the file location, e.g.:
  from apps.backend.data.repositories import foo as foo
  from apps.backend.data.repositories.module import Bar

Run locally: python tools/fix_barrels_absolute.py --apply
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
import SystemExit
import apply
import bool
import f
import int
import len
import list
import out_lines
import p
import path
import print
import str

ROOT = Path(__file__).resolve().parents[1]
ZETA_DIR = ROOT / "zeta_vn"

RE_AUTO = re.compile(r"AUTO-GENERATED by tools/autobarrel_python.py")
RE_FROM_DOT_IMPORT = re.compile(r"^from \. import (\w+)(?: as (\w+))?$")
RE_FROM_DOT_MODULE_IMPORT = re.compile(r"^from \.(\w+) import (.+)$")
RE_FROM_DOT_IMPORT_BLOCK = re.compile(r"^from \. import \($")
RE_FROM_DOT_MODULE_IMPORT_BLOCK = re.compile(r"^from \.(\w+) import \($")


def package_for(path: Path) -> str:
    # path is directory containing __init__.py, e.g. .../zeta_vn/data/repositories
    rel = path.relative_to(ZETA_DIR)
    parts = ["zeta_vn"] + list(rel.parts)
    return ".".join(parts)


def process_file(p: Path, apply: bool) -> bool:
    txt = p.read_text(encoding="utf8")
    if "AUTO-GENERATED by tools/autobarrel_python.py" not in txt:
        return False
    lines = txt.splitlines()
    pkg = package_for(p.parent)
    changed = False
    out_lines: list[str] = []
    i = 0
    n = len(lines)
    while i < n:
        ln = lines[i]
        s = ln.strip()
        # simple single-line patterns
        m = RE_FROM_DOT_IMPORT.match(s)
        if m:
            name = m.group(1)
            asname = m.group(2) or name
            new = f"from {pkg} import {name} as {asname}"
            out_lines.append(new)
            changed = changed or (new != ln)
            i += 1
            continue
        m2 = RE_FROM_DOT_MODULE_IMPORT.match(s)
        if m2:
            module = m2.group(1)
            rest = m2.group(2)
            new = f"from {pkg}.{module} import {rest}"
            out_lines.append(new)
            changed = changed or (new != ln)
            i += 1
            continue

        # multi-line import blocks: from . import ( ... )
        if RE_FROM_DOT_IMPORT_BLOCK.match(s):
            # collect until closing parenthesis
            block = [lines[i]]
            i += 1
            while i < n:
                block.append(lines[i])
                if lines[i].strip().endswith(")"):
                    break
                i += 1
            # rebuild with absolute package
            # keep inner lines as-is
            inner = block[1:]
            new_header = f"from {pkg} import ("
            out_lines.append(new_header)
            out_lines.extend(inner)
            changed = True
            i += 1
            continue

        # multi-line: from .module import ( ... )
        m3 = RE_FROM_DOT_MODULE_IMPORT_BLOCK.match(s)
        if m3:
            module = m3.group(1)
            block = [lines[i]]
            i += 1
            while i < n:
                block.append(lines[i])
                if lines[i].strip().endswith(")"):
                    break
                i += 1
            inner = block[1:]
            new_header = f"from {pkg}.{module} import ("
            out_lines.append(new_header)
            out_lines.extend(inner)
            changed = True
            i += 1
            continue

        # Aggressive fallback: convert any line that starts with 'from .' to absolute import
        if s.startswith("from ."):
            # replace only the leading 'from .' with 'from {pkg}'
            replaced = ln.replace("from .", f"from {pkg}", 1)
            out_lines.append(replaced)
            changed = True
        else:
            out_lines.append(ln)
        i += 1

    if changed and apply:
        p.write_text("\n".join(out_lines) + "\n", encoding="utf8")
    return changed


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    files = list(ZETA_DIR.rglob("__init__.py"))
    total = 0
    touched = 0
    for f in files:
        txt = f.read_text(encoding="utf8")
        if RE_AUTO.search(txt):
            total += 1
            changed = process_file(f, args.apply)
            if changed:
                touched += 1
                print(f"Patched: {f}")
    print(f"Scanned {total} auto-generated barrels, patched {touched} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
