# Generated by ScaffoldManager

from apps.backend.core.domain.ports.asr import ASRPort
import asr
import audio_path
import dict
import lang
import self
import str


class ASRService:
    def __init__(self, asr: ASRPort):
        self.asr = asr

    async def transcribe_and_learn(
        self, audio_path: str, *, lang: str | None = None
    ) -> dict:
        text = await self.asr.transcribe(audio_path, lang=lang)
        # TODO: nối Trainer: summarize -> ingest to KB / RLHF
        return {"text": text}
