#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")"/../.. && pwd)"
OUT="$ROOT/.artifacts/deadcode"
mkdir -p "$OUT"

echo "— Dead Code Detection —"

# Python dead code (vulture)
if command -v uv >/dev/null 2>&1; then
  echo "🐍 Scanning Python dead code with vulture..."
  (cd "$ROOT" && uvx vulture zeta_vn --min-confidence 80 --sort-by-size) | tee "$OUT/vulture.txt" || true
  
  # Summary
  DEAD_COUNT=$(wc -l < "$OUT/vulture.txt" || echo "0")
  echo "📊 Found $DEAD_COUNT potential dead code items in Python"
else
  echo "⚠️  uv not found, skipping Python dead code analysis"
  echo "(Python dead code analysis skipped - uv not available)" > "$OUT/vulture.txt"
fi

# Ensure ts-prune output exists (even if empty)
[ -f "$OUT/ts-prune.txt" ] || echo "(ts-prune not run yet - will be generated by ts_quality.sh)" > "$OUT/ts-prune.txt"

# Generate summary report
cat > "$OUT/SUMMARY.md" << 'EOF'
# Dead Code Analysis Summary

## Python (vulture)
- **File**: vulture.txt
- **Confidence**: ≥80%
- **Sorted by**: Size (largest dead code first)

## TypeScript (ts-prune) 
- **File**: ts-prune.txt
- **Generated by**: ts_quality.sh
- **Scope**: Unused exports detection

## Next Steps
1. Review vulture.txt for high-confidence dead code
2. Check ts-prune.txt for unused TypeScript exports
3. Remove confirmed dead code in small, safe commits
4. Re-run analysis to verify improvements

## Important Notes
- Vulture may have false positives for dynamic usage
- ts-prune may miss dynamic imports
- Always test after removing dead code
EOF

echo "📋 Dead-code reports → $OUT"
echo "📄 Summary report → $OUT/SUMMARY.md"
