"""
from __future__ import annotations

zeta_vn.core.security.authorization package.

Auto-fixed by comprehensive_init_fixer.py
"""

__all__ = [
    "ADMIN",
    "AI_MODEL",
    "ANALYTICS",
    "API_KEY",
    "APPROVE",
    "AUDIT_LOG",
    "AccessContext",
    "AccessControlManager",
    "AccessDecision",
    "ActionType",
    "CONVERSATION",
    "CREATE",
    "DELETE",
    "DOCUMENT",
    "EXECUTE",
    "GLOBAL",
    "MANAGE",
    "ORGANIZATION",
    "OWNER",
    "PERMISSION",
    "PROJECT",
    "Permission",
    "PermissionManager",
    "PermissionScope",
    "READ",
    "RESOURCE",
    "ROLE",
    "ResourceType",
    "Role",
    "RoleManager",
    "SYSTEM",
    "UPDATE",
    "USER",
    "UserRole",
    "all_permissions",
    "allowed",
    "applied_roles",
    "assign_role",
    "assignments",
    "check_permission",
    "context",
    "create_access_context",
    "create_access_control_manager",
    "create_permission",
    "create_role",
    "current_time",
    "decision",
    "default_permissions",
    "filtered_assignments",
    "filtered_log",
    "get_access_log",
    "get_effective_permissions",
    "get_permission",
    "get_permission_by_name",
    "get_role",
    "get_role_by_name",
    "get_user_effective_permissions",
    "get_user_roles",
    "has_permission",
    "list_permissions",
    "logger",
    "matching_permissions",
    "org_admin",
    "org_admin_permissions",
    "parent_permissions",
    "permission",
    "permissions",
    "project_manager",
    "project_permissions",
    "reason",
    "revoke_role",
    "role",
    "role_permissions",
    "super_admin",
    "super_admin_permissions",
    "user_permissions",
    "user_role",
    "user_role_assignments",
    "viewer_permissions",
    "viewer_role",
]
# >>> AUTO-GEN (ai_runner)
__all__ = [
    "rbac",
]

# <<< AUTO-GEN
