"""
from __future__ import annotations

zeta_vn.core.exceptions package.

Auto-fixed by comprehensive_init_fixer.py
"""

__all__ = [
    "AgentCreationError",
    "AgentDeploymentError",
    "AgentNotFoundError",
    "AsyncFunc",
    "AuthenticationError",
    "AuthorizationError",
    "BackupError",
    "BaseAuthError",
    "BaseBusinessError",
    "BaseRepositoryError",
    "BusinessException",
    "BusinessLogicError",
    "BusinessRuleViolationError",
    "CRITICAL",
    "CacheConnectionError",
    "CacheError",
    "ChatSessionError",
    "CircuitBreaker",
    "CircuitState",
    "ConnectionError",
    "ConnectionPoolExhaustedError",
    "DataIntegrityError",
    "DatabaseConnectionError",
    "DeadlockError",
    "DuplicateEntityError",
    "DuplicateRecordError",
    "EmbeddingDimensionError",
    "EntityNotFoundError",
    "ErrorSeverity",
    "ExceptionContext",
    "ExceptionHandler",
    "ExceptionTelemetry",
    "ExternalServiceError",
    "ForeignKeyViolationError",
    "HIGH",
    "InvalidCredentialsError",
    "InvalidTokenError",
    "JWTTokenError",
    "LOW",
    "MEDIUM",
    "MFARequiredError",
    "MemoryOperationError",
    "MessageProcessingError",
    "MigrationError",
    "ModelLoadError",
    "PermissionDeniedError",
    "PlanningError",
    "PromCounter",
    "PromHistogram",
    "QueryExecutionError",
    "QueryTimeoutError",
    "RateLimitExceededError",
    "RecordNotFoundError",
    "RepositoryError",
    "ResourceLimitExceededError",
    "STRUCTLOG_AVAILABLE",
    "SessionExpiredError",
    "T",
    "TrainingError",
    "TransactionError",
    "UserAlreadyExistsError",
    "ValidationError",
    "VectorDatabaseError",
    "VectorEmbeddingError",
    "WorkflowExecutionError",
    "aerror",
    "client_ip",
    "code",
    "context_id",
    "delay",
    "detail",
    "exception_counter",
    "exception_duration",
    "h",
    "log_level",
    "logger",
    "message",
    "payload",
    "register_exception_handlers",
    "request_id",
    "result",
    "retryable",
    "set_attribute",
    "sev",
    "sev_raw",
    "start",
    "start_as_current_span",
    "status_code",
    "user_agent",
]
# >>> AUTO-GEN (ai_runner)
__all__ = [
    "auth_exceptions",
    "business_exceptions",
    "context",
    "handlers",
    "repository_exceptions",
    "retry",
    "telemetry",
]

# <<< AUTO-GEN
