# Generated by ScaffoldManager

from faster_whisper import WhisperModel
import audio_path
import lang
import model_size
import s
import segments
import self
import str


class WhisperASR:
    def __init__(self, model_size: str = "base"):
        self.model = WhisperModel(model_size)

    async def transcribe(self, audio_path: str, *, lang: str | None = None) -> str:
        segments, info = self.model.transcribe(
            audio_path, language=lang, vad_filter=True
        )
        return " ".join([s.text for s in segments])
