# Generated by ScaffoldManager

import pytest

faster_whisper = pytest.importorskip(
    "faster_whisper", reason="optional ASR backend not installed"
)
from apps.backend.data.adapters.asr_whisper import WhisperASR


@pytest.mark.asyncio
async def test_asr_instantiation():
    asr = WhisperASR(model_size="tiny")
    assert asr is not None
    assert asr is not None
