#!/usr/bin/env python
"""
Sinh __init__.py (barrel) an toàn cho một số thư mục cho phép.
Chỉ chạy trên targets khai báo, tránh ghi đè bừa bãi.
"""

from __future__ import annotations

from pathlib import Path
import d
import dir_path
import f
import item
import len
import list
import m
import print
import s
import sorted
import str
import t

ROOT = Path.cwd()
INIT_FILE = "__init__.py"
MANUAL_MARKER = "# === manual exports below ==="
TARGETS = [
    "zeta_vn/app/validators",
    "zeta_vn/app/serializers",
    "zeta_vn/app/controllers",
    "zeta_vn/app/api/v1",
    "zeta_vn/app/api/v2",
    "zeta_vn/app/api/middleware",
    "zeta_vn/app/api/websockets",
    "zeta_vn/app/middleware",
    "zeta_vn/app/websockets",
    "zeta_vn/app/security",
    "zeta_vn/app/observability",
    "zeta_vn/app/services",
    "zeta_vn/app/exceptions",
    "zeta_vn/core/services",
    "zeta_vn/core/use_cases",
    "zeta_vn/core/use_cases/agents",
    "zeta_vn/core/use_cases/chat",
    "zeta_vn/core/interfaces",
    "zeta_vn/core/domain/entities",
    "zeta_vn/core/observability",
    "zeta_vn/data/repositories",
    "zeta_vn/data/models",
    "zeta_vn/data/external",
    "zeta_vn/data/services",
    "zeta_vn/data/shared",
    "zeta_vn/data/utils",
    "zeta_vn/tests/mocks",
    "zeta_vn/tests/unit",
    "zeta_vn/tests/unit/agents",
    "zeta_vn/config/settings",
    # Có thể bổ sung thêm targets khác
]

HEADER = "# ⚠️ AUTO-GENERATED by tools/autobarrel_python.py. Do not edit.\n"


def _find_modules(dir_path: Path) -> list[str]:
    """Tìm tất cả modules Python trong thư mục."""
    modules = []
    for f in sorted(dir_path.glob("*.py")):
        if f.name.startswith("_") or f.name == INIT_FILE:
            continue
        modules.append(f.stem)
    return modules


def _find_subpackages(dir_path: Path) -> list[str]:
    """Tìm tất cả subpackages trong thư mục."""
    subpackages = []
    for d in sorted(dir_path.iterdir()):
        if d.is_dir() and (d / INIT_FILE).exists():
            subpackages.append(d.name)
    return subpackages


def _get_manual_content(init_path: Path) -> str:
    """Lấy nội dung thủ công từ __init__.py hiện có."""
    if not init_path.exists():
        return ""

    txt = init_path.read_text(encoding="utf-8")
    if MANUAL_MARKER not in txt:
        return ""

    return txt.split(MANUAL_MARKER, 1)[1]


def _generate_imports(modules: list[str], subpackages: list[str], package_path: str) -> list[str]:
    """Tạo các dòng import absolute."""
    lines = []
    for m in modules:
        lines.append(f"from {package_path}.{m} import *\n")
    for s in subpackages:
        lines.append(f"from {package_path} import {s}\n")
    return lines


def _generate_all_list(modules: list[str], subpackages: list[str]) -> list[str]:
    """Tạo __all__ list."""
    lines = ["\n__all__ = [\n"]
    for item in modules + subpackages:
        lines.append(f"    '{item}',\n")
    lines.append("]\n\n")
    return lines


def gen_barrel(dir_path: Path) -> None:
    """Tạo hoặc cập nhật __init__.py barrel cho thư mục."""
    if not dir_path.exists():
        print(f"Skipping non-existent directory: {dir_path}")
        return

    modules = _find_modules(dir_path)
    subpackages = _find_subpackages(dir_path)

    if not modules and not subpackages:
        print(f"No modules or subpackages found in: {dir_path}")
        return

    # Convert path to package name
    rel_path = dir_path.relative_to(ROOT)
    package_path = str(rel_path).replace("\\", ".").replace("/", ".")

    init_path = dir_path / INIT_FILE
    # An toàn: nếu đã có __init__.py nhưng không mang HEADER và cũng không có marker,
    # coi như file thủ công -> bỏ qua để tránh ghi đè logic tùy biến
    if init_path.exists():
        existing = init_path.read_text(encoding="utf-8")
        if (HEADER not in existing) and (MANUAL_MARKER not in existing):
            print(f"Skipping existing non-autobarrel init: {init_path}")
            return
    manual = _get_manual_content(init_path)

    # Tạo nội dung file
    lines = [HEADER, "\n"]
    lines.extend(_generate_imports(modules, subpackages, package_path))
    lines.extend(_generate_all_list(modules, subpackages))
    lines.append(MANUAL_MARKER)
    lines.append(manual)

    init_path.write_text("".join(lines), encoding="utf-8")
    print(f"Updated barrel: {init_path} ({len(modules)} modules, {len(subpackages)} subpackages)")


def main() -> None:
    for t in TARGETS:
        p = ROOT / t
        if p.is_dir():
            gen_barrel(p)


if __name__ == "__main__":
    main()
