#!/usr/bin/env python3
"""
Git Patch Recovery System

Tạo patch files để khôi phục nội dung bị auto-fix làm mất.
Phân tích các file bị regression và tạo patches từ git history.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
import Exception
import SystemExit
import cmd
import commit
import e
import from_commit
import i
import int
import issue
import len
import print
import str

SRC = Path(".artifacts/auto_fix_regression.json")
OUT_DIR = Path(".artifacts/restore_patches")
OUT_DIR.mkdir(parents=True, exist_ok=True)


def run_git_command(cmd: str) -> str:
    """Chạy git command và trả về output."""
    # Security: only allow git commands
    if not cmd.startswith("git "):
        return ""

    try:
        result = subprocess.run(  # noqa: S603
            cmd.split(),
            capture_output=True,
            text=True,
            check=False,
            cwd=Path.cwd(),
        )
        return result.stdout.strip()
    except Exception as e:
        print(f"❌ Git command failed: {cmd} - {e}")
        return ""


def get_file_at_commit(file_path: str, commit: str = "HEAD~1") -> str:
    """Lấy nội dung file tại commit cụ thể."""
    return run_git_command(f"git show {commit}:{file_path}")


def get_diff_patch(file_path: str, from_commit: str = "HEAD~1") -> str:
    """Tạo patch diff cho file từ commit cũ đến hiện tại."""
    return run_git_command(f"git diff {from_commit} -- {file_path}")


def analyze_regression_severity(current_content: str, previous_content: str) -> str:
    """Phân tích mức độ nghiêm trọng của regression."""
    if not previous_content:
        return "UNKNOWN"

    current_lines = len(current_content.splitlines())
    previous_lines = len(previous_content.splitlines())

    if current_lines == 0:
        return "CRITICAL"  # File bị xóa hoàn toàn

    reduction_ratio = (previous_lines - current_lines) / previous_lines

    if reduction_ratio > 0.8:
        return "CRITICAL"
    elif reduction_ratio > 0.6:
        return "HIGH"
    elif reduction_ratio > 0.3:
        return "MEDIUM"
    else:
        return "LOW"


def create_restoration_script(file_path: str, previous_content: str) -> str:
    """Tạo script phục hồi cho file."""
    script = f"""#!/bin/bash
# Restoration script for {file_path}
# Generated by restore_candidate_patch.py

echo "🔧 Restoring {file_path}..."

# Backup current version
if [ -f "{file_path}" ]; then
    cp "{file_path}" "{file_path}.backup.$(date +%s)"
    echo "✓ Created backup: {file_path}.backup"
fi

# Restore from previous content
cat > "{file_path}" << 'EOF'
{previous_content}
EOF

echo "✅ Restored {file_path} from git history"
echo "⚠️  Please review and test the restored content"
"""
    return script


def main() -> int:
    """Tạo patches và scripts khôi phục cho regression files."""
    if not SRC.exists():
        print("❌ auto_fix_regression.json not found")
        print("   Run auto_fix_regression_guard.py first")
        return 2

    try:
        data = json.loads(SRC.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"❌ Error reading regression report: {e}")
        return 1

    issues = data.get("issues", [])
    high_severity = [i for i in issues if i["severity"] == "HIGH"]

    if not high_severity:
        print("✅ No HIGH severity regressions found")
        print("   No patch recovery needed")
        return 0

    print(f"🔍 Found {len(high_severity)} HIGH severity regressions")
    created_patches = 0
    created_scripts = 0

    for issue in high_severity:
        file_path = issue["file"]
        print(f"📄 Processing {file_path}...")

        # Get patch diff
        patch_content = get_diff_patch(file_path)

        # Get previous file content
        previous_content = get_file_at_commit(file_path)

        if not patch_content and not previous_content:
            print(f"   ⚠️  No git history found for {file_path}")
            continue

        # Safe filename for artifacts
        safe_name = file_path.replace("/", "_").replace("\\", "_")

        # Create patch file
        if patch_content:
            patch_file = OUT_DIR / f"{safe_name}.patch"
            patch_file.write_text(patch_content, encoding="utf-8")
            print(f"   ✓ Created patch: {patch_file.name}")
            created_patches += 1

        # Create restoration script
        if previous_content:
            # Analyze severity
            try:
                current_content = Path(file_path).read_text(encoding="utf-8")
            except Exception:
                current_content = ""

            severity = analyze_regression_severity(current_content, previous_content)

            # Create restoration script
            script_content = create_restoration_script(file_path, previous_content)
            script_file = OUT_DIR / f"{safe_name}.restore.sh"
            script_file.write_text(script_content, encoding="utf-8")

            # Make script executable (on Unix systems)
            try:
                script_file.chmod(0o755)
            except Exception:
                pass  # Windows doesn't support chmod

            print(f"   ✓ Created restore script: {script_file.name} ({severity})")
            created_scripts += 1

            # Also create the raw previous content
            prev_file = OUT_DIR / f"{safe_name}.previous"
            prev_file.write_text(previous_content, encoding="utf-8")

    # Create summary report
    summary = {
        "timestamp": "2025-08-29",
        "processed_files": len(high_severity),
        "patches_created": created_patches,
        "scripts_created": created_scripts,
        "instructions": [
            f"Review patches in {OUT_DIR}",
            "Apply patches with: git apply <patch_file>",
            "Or run restore scripts: bash <file>.restore.sh",
            "Always test restored content before committing",
        ],
    }

    summary_file = OUT_DIR / "recovery_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    # Create README
    readme_content = f"""# Git Patch Recovery

Generated restoration artifacts for {len(high_severity)} files with HIGH severity regressions.

## Files Created

- **Patches** ({created_patches}): Apply with `git apply <file>.patch`
- **Restore Scripts** ({created_scripts}): Run with `bash <file>.restore.sh`
- **Previous Content**: Raw content from git history

## Usage

1. **Review changes**:
   ```bash
   ls {OUT_DIR}
   ```

2. **Apply specific patch**:
   ```bash
   git apply {OUT_DIR}/<file>.patch
   ```

3. **Or restore entire file**:
   ```bash
   bash {OUT_DIR}/<file>.restore.sh
   ```

4. **Verify results**:
   ```bash
   git diff
   uv run pytest -x
   ```

## ⚠️ Important

- Always backup before applying patches
- Test restored code thoroughly
- Some patches may need manual resolution
- Review git history to understand what was lost

"""

    readme_file = OUT_DIR / "README.md"
    readme_file.write_text(readme_content, encoding="utf-8")

    print("\n📊 Patch Recovery Summary:")
    print(f"   📄 Files processed: {len(high_severity)}")
    print(f"   🔧 Patches created: {created_patches}")
    print(f"   📜 Scripts created: {created_scripts}")
    print(f"   📁 Output directory: {OUT_DIR}")
    print(f"   📖 See {readme_file} for usage instructions")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
