#!/usr/bin/env python3
"""
Directory Scaffolding System

Tự động tạo cấu trúc thư mục và files skeleton theo file_expectations.yaml
Đảm bảo minimal structure để build không lỗi.
"""

from __future__ import annotations

from pathlib import Path

import yaml
import Exception
import SystemExit
import action
import e
import f
import file_name
import int
import len
import package_name
import package_path
import print
import spec
import str
import template_name

CFG = Path("configs/file_expectations.yaml")
ROOT = Path("zeta_vn")
ART = Path(".artifacts")
ART.mkdir(parents=True, exist_ok=True)
OUT = ART / "scaffold_dir_actions.md"

# Template skeletons cho các loại file khác nhau
TEMPLATES = {
    "router.py": '''"""FastAPI router module."""
from __future__ import annotations

from fastapi import APIRouter

router = APIRouter()


@router.get("/health")
def health_check() -> dict[str, bool]:
    """Health check endpoint."""
    return {"ok": True}
''',
    "status.py": '''"""Status module cho API."""
from __future__ import annotations

from fastapi import APIRouter

router = APIRouter()


@router.get("/")
def get_status() -> dict[str, str]:
    """Trả về status của service."""
    return {"status": "ok", "service": "api"}
''',
    "adapter.py": '''"""Base adapter implementation."""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class BaseAdapter(ABC):
    """Base adapter interface."""
    
    @abstractmethod
    async def process(self, data: Any) -> Any:
        """Process data through adapter."""
        ...
''',
    "service.py": '''"""Service layer implementation."""
from __future__ import annotations

from typing import Any


class BaseService:
    """Base service class."""
    
    def __init__(self) -> None:
        """Initialize service."""
        pass
    
    async def execute(self, request: Any) -> Any:
        """Execute service operation."""
        raise NotImplementedError("Service method not implemented")
''',
    "entity.py": '''"""Domain entity."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class BaseEntity:
    """Base domain entity."""
    
    id: str
    
    def to_dict(self) -> dict[str, Any]:
        """Convert entity to dictionary."""
        return {"id": self.id}
''',
    "repository.py": '''"""Repository interface."""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Optional


class BaseRepository(ABC):
    """Base repository interface."""
    
    @abstractmethod
    async def get(self, id: str) -> Optional[Any]:
        """Get entity by ID."""
        ...
    
    @abstractmethod
    async def save(self, entity: Any) -> Any:
        """Save entity."""
        ...
''',
    "use_case.py": '''"""Use case implementation."""
from __future__ import annotations

from typing import Any


class BaseUseCase:
    """Base use case."""
    
    async def execute(self, request: Any) -> Any:
        """Execute use case."""
        raise NotImplementedError("Use case not implemented")
''',
}


def guess_template_type(file_name: str, package_path: str) -> str:
    """Đoán loại template dựa trên tên file và đường dẫn package."""
    file_lower = file_name.lower()
    package_lower = package_path.lower()

    # Exact matches
    if file_lower in TEMPLATES:
        return file_lower

    # Pattern matching
    if "router" in file_lower or "api" in package_lower:
        return "router.py"
    elif "adapter" in file_lower or "adapters" in package_lower:
        return "adapter.py"
    elif "service" in file_lower or "services" in package_lower:
        return "service.py"
    elif "entity" in file_lower or "entities" in package_lower:
        return "entity.py"
    elif "repository" in file_lower or "repositories" in package_lower:
        return "repository.py"
    elif "use_case" in file_lower or "use_cases" in package_lower:
        return "use_case.py"
    else:
        return "router.py"  # Default fallback


def create_init_file(directory: Path) -> str:
    """Tạo nội dung __init__.py dựa trên structure của directory."""
    return '''"""Package initialization."""
from __future__ import annotations

# Auto-generated by scaffold system
'''


def main() -> int:
    """Tạo scaffolding cho directory structure thiếu."""
    if not CFG.exists():
        print("❌ configs/file_expectations.yaml not found")
        print("   Run generate_expectations_from_project_map.py first")
        return 2

    try:
        with CFG.open(encoding="utf-8") as f:
            config = yaml.safe_load(f) or {}
    except Exception as e:
        print(f"❌ Error reading config: {e}")
        return 1

    actions = []
    created_files = 0

    # Process dir_minimal requirements
    dir_minimal = config.get("dir_minimal", {})

    for package_name, spec in dir_minimal.items():
        must_have_files = spec.get("must_have_files", [])

        # Convert package name to directory path
        directory = ROOT / package_name.replace(".", "/")

        # Ensure directory exists
        if not directory.exists():
            directory.mkdir(parents=True, exist_ok=True)
            actions.append(f"📁 Created directory: {directory}")

        # Ensure __init__.py exists
        init_file = directory / "__init__.py"
        if not init_file.exists():
            init_content = create_init_file(directory)
            init_file.write_text(init_content, encoding="utf-8")
            actions.append(f"📄 Created __init__.py: {init_file}")
            created_files += 1

        # Create required files
        for file_name in must_have_files:
            file_path = directory / file_name

            if file_path.exists():
                actions.append(f"✓ Exists: {file_path}")
                continue

            # Guess appropriate template
            template_type = guess_template_type(file_name, package_name)
            template_content = TEMPLATES.get(template_type, TEMPLATES["router.py"])

            # Add custom comment for generated files
            header = f"""# Auto-generated skeleton for {package_name}.{file_name}
# Created by scaffold_missing_dirs.py
# TODO: Implement actual functionality

"""

            full_content = header + template_content

            try:
                file_path.write_text(full_content, encoding="utf-8")
                actions.append(f"✅ Created: {file_path} (using {template_type} template)")
                created_files += 1
            except Exception as e:
                actions.append(f"❌ Failed to create {file_path}: {e}")

    # Generate action report
    report_lines = [
        "# Directory Scaffolding Actions",
        "",
        "Generated on: 2025-08-29",
        f"Files created: {created_files}",
        "",
        "## Actions Performed",
        "",
    ]

    for action in actions:
        report_lines.append(f"- {action}")

    if not actions:
        report_lines.append("- ✅ No scaffolding needed - all requirements satisfied")

    report_lines.extend(
        [
            "",
            "## Next Steps",
            "",
            "1. Review generated files and implement actual functionality",
            "2. Add proper error handling and validation",
            "3. Write tests for new modules",
            "4. Update imports and exports as needed",
            "5. Remove TODO comments after implementation",
            "",
            "## Templates Used",
            "",
        ]
    )

    for template_name in TEMPLATES:
        report_lines.append(f"- `{template_name}`: {template_name.replace('.py', '').title()} template")

    # Write report
    OUT.write_text("\n".join(report_lines), encoding="utf-8")

    # Console output
    print("🔧 Directory Scaffolding Complete")
    print(f"   Files created: {created_files}")
    print(f"   Actions performed: {len(actions)}")
    print(f"   Report: {OUT}")

    if created_files > 0:
        print("\n⚠️  Generated files contain skeleton code only")
        print("   Review and implement actual functionality")
        print("   Remove TODO comments after implementation")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
